version: "{build}"
image: Visual Studio 2017
platform: x64

clone_folder: C:\projects\cquery

install:
  - git submodule update --init

environment:
  CLICOLOR_FORCE: 1
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: MSVC

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x64

build_script:
  - ps: |
      If ($Env:MSYSTEM -Eq "MSVC") {
        $dir = "cquery-${env:appveyor_build_version}-win64"
        cd C:\projects\cquery
        python waf configure --msvc_version="msvc 15.0"
        python waf build
        mkdir "${dir}\build\release\bin" -ea 0
        mkdir "${dir}\build\release\lib\LLVM-6.0.0-win64\lib\clang\6.0.0\"
        copy "build\release\bin\*" "${dir}\build\release\bin"
        copy -recurse "build\LLVM-6.0.0-win64\lib\clang\6.0.0\include" "${dir}\build\release\lib\LLVM-6.0.0-win64\lib\clang\6.0.0\"
        7z a -tzip "C:\projects\cquery\${dir}.zip" "${dir}"
      } Else {
        C:\msys64\usr\bin\bash -lc @'
        pacman -S --needed --noconfirm mingw-w64-x86_64-clang python
        cd /c/projects/cquery
        CXXFLAGS=-Wall /usr/bin/python waf configure build --llvm-config llvm-config 2>&1
      '@
      }
  - set PATH=%PATH%;C:\msys64\%MSYSTEM%\bin
  - build\release\bin\cquery --ci --log-all-to-stderr --test-unit
  - IF "%MSYSTEM%"=="MSVC" build\release\bin\cquery --ci --log-all-to-stderr --test-index

artifacts:
  - path: 'cquery-*.zip'

cache:
  - C:\projects\cquery\build\LLVM-6.0.0-win64.exe
  - C:\projects\cquery\build\LLVM-6.0.0-win64\
