dist: trusty
sudo: false
language: c++

env:
  global:
  - COMPILER=g++

# Default --recursive (rapidjson/thirdparty/gtest) is unnecessary
git:
  submodules: false
  depth: 1

before_install:
  - git submodule update --init

addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-trusty-5.0

compiler: clang
os: linux

cache:
  directories:
    - build/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/
    - build/clang+llvm-6.0.0-x86_64-apple-darwin/

matrix:
  fast_finish: true
  include:
    - env: COMPILER=g++-5
      compiler: gcc
      addons: &gcc5
        apt:
          packages: ["g++-5"]
          sources: *apt_sources

    - env: COMPILER=g++-7
      compiler: gcc
      addons: &gcc7
        apt:
          packages: ["g++-7"]
          sources: *apt_sources

    - env: COMPILER=clang++-3.5
      addons: &clang35
        apt:
          packages: ["clang-3.5", "g++-7"]
          sources: *apt_sources

    - env: COMPILER=clang++-5.0
      addons: &clang50
        apt:
          packages: ["clang-5.0", "g++-7"]
          sources: *apt_sources

    - env: COMPILER=clang++
      osx_image: xcode9.1
      os: osx

    - env: COMPILER=g++-7
      compiler: gcc
      osx_image: xcode9.1
      os: osx


  allow_failures:

    # macOS takes too long.

    #- env: COMPILER=clang++
    #  osx_image: xcode9.1
    #  os: osx

    #- env: COMPILER=g++-7
    #  compiler: gcc
    #  osx_image: xcode9.1
    #  os: osx

    # gcc builds that should be fixed at some point

    #- env: COMPILER=g++-5
    #  compiler: gcc

    #- env: COMPILER=g++-6
    #  compiler: gcc

    #- env: COMPILER=g++-7
    #  compiler: gcc

    #- env: COMPILER=g++-5
    #  compiler: gcc
    #  osx_image: xcode9.1
    #  os: osx

    #- env: COMPILER=g++-6
    #  compiler: gcc
    #  osx_image: xcode9.1
    #  os: osx

    #- env: COMPILER=g++-7
    #  compiler: gcc
    #  osx_image: xcode9.1
    #  os: osx

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      if [[ "${COMPILER}" == "g++-5" ]]; then
        brew install gcc@5
        brew link --overwrite gcc@5
      fi
      if [[ "${COMPILER}" == "g++-6" ]]; then
        brew install gcc@6
        brew link --overwrite gcc@6
      fi
      if [[ "${COMPILER}" == "g++-7" ]]; then
        brew install gcc@7
        brew link --overwrite gcc@7
      fi
    fi

  - |
    if [[ "${COMPILER}" == g++* ]]; then
      export J="-j1"
    fi

  - export CXX="${COMPILER}"

before_script:
  - ${CXX} --version

script:
  - travis_retry ./waf configure
  - ./waf build ${J}
  - ./build/release/bin/cquery --ci --log-all-to-stderr --test-unit
  - ./build/release/bin/cquery --ci --log-all-to-stderr --test-index

notifications:
  email: false
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#cquery"
    template:
      - "[ %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url} )"

before_deploy:
  #- zip -r build/cquery-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip build/release/bin/ build/release/lib/clang+llvm-*/lib/libclang.* build/release/lib/clang+llvm-*/lib/clang/5.0.1/include/
  - ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: Ahv4Wp1wveWILqp6HB8UmsXwwfZ103fuJV/u6W4oJFRpnbIXRCGFKaDR1Ql0hsHduKFd/76nNQGSVvNNuTXlWaK2n0bTu1EZ4VYmXk7Q7gn4ROP9XFrIZu0c9XKJ/bzehCLj3t6KT0R5MK5gQe+cBmx4S5uGsGG5/nM+GZpE1N4craRCh64UNXMvIx20sW4VQcgj1Ccrc/6Skb3HET7PKbY+IB/LXnaF3nM6V71LxKW2wlakBmzzaNatQ46QOcOCduY4edE8FqBs7yZ0eFktNZusmjiaZT12t0r1hVe0O8e0ER3u9/c3t+hbPUplMR2FAPBZXojgLVhSfFtBaj45T74oCIi0eUaDeS+Oxl6IzgyVho9RurOtaru3hLOVoaD9wR6lGhj6Nz/2Na3lOIorxHfAZ4OgUmluoFLCynO4ylMD03fMBGBshChnmYbrxLw0xLZP2005WUAj8JN64QOmFmLt3gV7TfVldSFHuwoZyESfkXPRM1Xn8RtgFi/89p4jtPtyBFLSaeDggCwfWEMfADCfJ/j8lXtAPdyEINoaKrxkH8qCPoMLNPXE7JhkP8L0Smdq4cFUEXg3wKWM2hXmWmh2Y25BAyh4qu9CrDPd5qqFcXMtyix4ZjmThLFs/oKYbbMUo4FQ5xT5dpt/VZOi4NpcAj0G/M3jWhu85tMdtTc=
  #file: build/cquery-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip
  file: build/cquery-$TRAVIS_TAG-x86_64-apple-darwin.tar.xz
  file: build/cquery-$TRAVIS_TAG-x86_64-unknown-linux-gnu.tar.xz
  skip_cleanup: true
  on:
    repo: cquery-project/cquery
    tags: true

